
version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
